function tracks = initializeTracks()
% create an empty array of tracks
tracks = struct(...
    'id', {},...
    'kalmanFilter', {},...
    'age', {},...
    'totalVisibleCount', {},...
    'consecutiveInvisibleCount', {},);
end